name: demo

on:
  workflow_dispatch:

#on:
#  push:
#    branches:
#      - master

jobs:
  demo-job:
    name: demo job
    runs_on: self-hosted
    timeout-minutes: 20
    steps:
      - name: start
        run: echo "DEMO APPLICATION INITIALIZE"

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build with gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.5
        run: |
          gradle clean build -Pprofile=dev -x test --info
          ls -l
      - name: connect ssh and execute deploy shell
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEMO_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.DEMO_SERVER_IP }}
          REMOTE_USER: ${{ secrets.DEMO_SERVER_USERNAME }}
          TARGET: ${{ secrets.DEMO_SERVER_TARGET_DIR }}
          SOURCE: target/*.jar
          ARGS: -rlgoDzvc
          SCRIPT_BEFORE: |
            echo "==== Rsync Step Start ===="
            ls -al
          SCRIPT_AFTER: |
            ls -al
            echo "==== Rsync Step End ===="
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEMO_SERVER_IP }}
          username: ${{ secrets.DEMO_SERVER_USERNAME }}
          key: ${{ secrets.DEMO_SSH_PRIVATE_KEY }}
          script: |
            cd $${{ secrets.DEMO_SERVER_TARGET_DIR }}
            ls -al
            echo "run shell"
            echo `./run.sh`
      - name: check server ready
        uses: Jtalk/url-health-check-action@v4
        with:
          url: http://$${{ secret.DEMO_SERVER_IP }}:8080
          max-attempts: 3
          retry-delay: 10s